### ISSUE TITLE
3.10.0 breaks our current implementation

### ISSUE THREAD

**Issue by maddieholtzer** [magnusvk/counter_culture#408]
With the update to 3.10.0 we see that a substantial portion of our tests are breaking.

Doing some testing with this it appears that this may be because we are using `counter_culture` without explicitly adding the association.

When doing the upgrade with just:

```
#app/models/form_request.rb

counter_culture [:campaign]
```

we get this failure:

```
Failure/Error: let(:form_request) { create(:form_request) }
     
ActiveRecord::AssociationNotFoundError: Association named 'campaign' was not found on FormRequest; perhaps you misspelled it?
```

When updated to include the association:

```
belongs_to :campaign
counter_culture [:campaign]
```

things now work in `3.10.0`

Curious whether our current implementation was ever intended to be supported our not.

**Comment by vitalinfo** [comment]
@maddieholtzer could you please provide more backtrace, because I can't reproduce such error 

Without `belongs_to` I get an exception:

```
  1) CounterCulture 
     Failure/Error: value = value.send(relation.shift)
     
     NoMethodError:
       undefined method `post' for an instance of PostLike
     # .../gems/ruby-3.3.1/gems/activemodel-6.0.6.1/lib/active_model/attribute_methods.rb:432:in `method_missing'
     # ./lib/counter_culture/counter.rb:202:in `foreign_key_value'
     # ./lib/counter_culture/counter.rb:50:in `change_counter_cache'
     # ./lib/counter_culture/extensions.rb:111:in `block in _update_counts_after_create'
     # ./lib/counter_culture/extensions.rb:109:in `each'
     # ./lib/counter_culture/extensions.rb:109:in `_update_counts_after_create'
     # ./lib/counter_culture/skip_updates.rb:8:in `_update_counts_after_create'
```

but this's definitely doesn't related to this changes https://github.com/magnusvk/counter_culture/pull/407 and as for me pretty expected

**Comment by magnusvk** [comment]
@maddieholtzer I tried reproducing this, see #409. But you can see there that this fails both with and without the changes in #407.

My first instinct here is to say "I would have never expected that to work, and why don't you just add the association?" At the same time, if there's an easy fix for this I'm certainly not opposed to adding that.

**Comment by maddieholtzer** [comment]
Hello @magnusvk 

I have just put up a pr showcasing the issue we are experiencing [here](https://github.com/magnusvk/counter_culture/pull/410)

The change in 3.10.0 appears to have broken implementations where delegations are used on multi-level counters.
