### ISSUE TITLE
Undefined Method `current_time_from_proper_timezone' Error

### ISSUE THREAD

**Issue by byungjikroh** [magnusvk/counter_culture#387]
I'm using Ruby 2.6.6 and Rails 4.2.11 and I've got 
NoMethodError - undefined method `current_time_from_proper_timezone' 
when I updated the version to 3.5.1 from 3.5.0. 

It seems that it is related with this commit. (https://github.com/magnusvk/counter_culture/pull/383)

Is there any way to solve this error?

**Comment by magnusvk** [comment]
I'm sorry, but the best answer I have for you is "upgrade your Ruby and Rails." Ruby 2.6 has been end of life for almost two years, and Rails 4.2 for over six years. I support a number of older, end-of-life Ruby and Rails versions, but these are too old. I know that's a pain, but it's worth investing in the upgrade.
